### ISSUE TITLE
Password Reset - OpenHub: function not working

### ISSUE THREAD

**Issue by Wolf-at-SO** [blackducksoftware/ohloh-ui#1296]
I tried to reset my OpenHub password (my account is dating back to Ohloh times). I enter my email address into the reset form and submit it,
> You will receive an email within the next few minutes. It contains instructions for changing your password.

I then get an email (some seconds later), I click on the link within the email, right under
> Someone, hopefully you, requested we send you a link to change your password:

I get to another web page, where I see the error message
>  Your password reset URL has expired. Please try again! 

under that the known form
> To be emailed a link to reset your password, please enter your email address.

this repeats probably endlessly. I stopped after the 3rd try.

**Comment by jonathancross** [comment]
Happy 2019!  @Wolf-at-SO is this still an issue for you?

**Comment by nylon0700** [comment]
It is an issue for me... OHLOH account. Reset request doesnt work

**Comment by PDegenPortnoy** [comment]
The Open Hub has moved into a different production environment. Please let us know if this is still an issue for anyone.

**Comment by PDegenPortnoy** [comment]
Closing issue as it approaches 2 years old and we've made a number of updates and fixes around login and password behavior.
