### ISSUE TITLE
Add missing languages

### ISSUE THREAD

**Issue by OlaFosheimGrostad** [blackducksoftware/ohloh-ui#1428]
Nim
Swift
Dart

**Comment by PDegenPortnoy** [comment]
Hi @OlaFosheimGrostad, thanks for writing. Ohloh UI uses the [Ohcount](https://github.com/blackducksoftware/ohcount) source code counting tool. If you would like to have these languages be detected and represented in Ohloh UI, may I ask that you consider adding them to the Ohcount project (which is Open Source)?

**Comment by PDegenPortnoy** [comment]
Closing issue as this should be addressed in the Ohcount source code
