### ISSUE TITLE
Remove API limit of 1000 queries for Shields.io

### ISSUE THREAD

**Issue by Paebbels** [blackducksoftware/ohloh-ui#1491]
The service [Shields.io](https://shields.io/) would like to create unified badges for OpenHub like:
* `Open Hub | rank 7 `  
  ![](https://img.shields.io/badge/OpenHub-rank%207-blue)
* `Open Hub | 1059 commits`  
  ![](https://img.shields.io/badge/OpenHub-1059%20commits-blue)

This is currently not possible, because OpenHub limits API access to 1000 queries.  
**Is it possible to remove this limit for Shields.io?**

See also: https://github.com/badges/shields/issues/4480

**Comment by paulmelnikow** [comment]
Hello from Shields! If you can provide an API token for us with a higher limit, or a set of tokens we can rotate through, we'd be happy to provide this badge as users have requested.

**Comment by PDegenPortnoy** [comment]
Hi Shields! Nice to hear from you and we'd love to help. We can increase the API limits for your account to accommodate your request. Please contact us a info@openhub.net and we'll dig into the details.

**Comment by PDegenPortnoy** [comment]
We will also look at creating a badge that fit the canonical design for use in Readme's. That would probably be a better long-term solution.

**Comment by mohawk2** [comment]
I assume this is solved so the issue could be closed? :-)

**Comment by Paebbels** [comment]
I think so.

**Comment by mohawk2** [comment]
@Paebbels So you could... click the "close" button? ;-)
